theme: jekyll-theme-minimal
title: SLOP! - A Fresh Take on Chia Pudding
description: The health nut's new obsession - chia seed pudding that's actually exciting, packed with protein, and ridiculously good for you. Coming soon to Essex Market! 